on:
  push:
    branches:
      - main
    paths:
      - website/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
            az storage blob upload-batch --account-name saprodwebapp --destination '$web' --source website --overwrite
